apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-api-gateway-deployment # deployment의 이름
spec:
  replicas: 1 # 복제본 1개
  selector:
    matchLabels:
      app: k8s-api-gateway # template label 이름과 동일해야함
  template:
    metadata:
      labels:
        app: k8s-api-gateway
    spec:
      containers:
      - name: k8s-api-gateway # 컨테이너 이름
        image: suhyunkim7288/k8s-api-gateway:0.0.1 # 사용할 이미지
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        ports:
        - containerPort: 8080